//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacteristicsTI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CharacteristicsTI()
        {
            this.ResultsTI = new HashSet<ResultsTI>();
        }
    
        public int idCharacteristicsTI { get; set; }
        public bool brakeSystems { get; set; }
        public bool steering { get; set; }
        public bool lightDevices { get; set; }
        public bool windscreenWipers { get; set; }
        public bool tiresAndWheels { get; set; }
        public bool engine { get; set; }
        public bool structuralElements { get; set; }
        public bool safetyRequirements { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultsTI> ResultsTI { get; set; }
    }
}
