//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticMap
    {
        public int idDiagnosticMap { get; set; }
        public int Driver_idDriver { get; set; }
        public string stateCarNumber { get; set; }
        public string engineNumber { get; set; }
        public string color { get; set; }
        public string carModel { get; set; }
    
        public virtual Driver Driver { get; set; }
    }
}
